include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    missing_required_param: warning
    missing_return: warning
    unnecessary_import: ignore
linter:
  rules:
    sort_unnamed_constructors_first: false
    sort_constructors_first: false
    prefer_const_constructors: false
    avoid_classes_with_only_static_members: false
    avoid_bool_literals_in_conditional_expressions: false
    eol_at_end_of_file: false
    avoid_print: false
    directives_ordering: false
    sort_pub_dependencies: false
    use_setters_to_change_properties: false