include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    missing_return: warning
    unnecessary_import: ignore
linter:
  rules:
    sort_constructors_first: true
    prefer_const_constructors: false
